### PR TITLE
App controllers

### PR DESCRIPTION
**Pull request by fernando-silvabr66**
Create controllers, actions and views for Users.
Create controllers, actions and views for Posts.
Update routes.rb file.
Create placeholders for users and posts according to the wireframes (text only).

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
# Hello @fernando-silvabr66  😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [x] In the README file, Please add a description to the project and write steps on how someone can run your project on their machine. 👍🏻 

_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fernando-silvabr66** [comment]
Hi @zainsadaqat Thanks for your comments. Just to be sure of what I should do... the README.md already have a basic description of the app and also the basic steps to have the app up and running, as follow:

image

image

Could you provide additional specifics on what you suggest I should do? Thanks in advance.

**Comment by fernando-silvabr66** [comment]
As I have nor heard back I've included some additional comments (details) on how to set the app up into the README.md file.

**Review by OLIPLICHE — APPROVED** [review]
Hi @fernando-silvabr66, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Implemented the change requested 👏 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
