### PR TITLE
Validations and specs work

### PR DESCRIPTION
**Pull request by fernando-silvabr66**
Add validations:

- For the User model:

> Name must not be blank.

> PostsCounter must be an integer greater than or equal to zero.

- For the Post model:

> Title must not be blank.

> Title must not exceed 250 characters.

> CommentsCounter must be an integer greater than or equal to zero.

> LikesCounter must be an integer greater than or equal to zero.

Add unit specs for all models' methods and validations.

### CODE REVIEW

**Review by SajjadAhmad14 — COMMENTED** [review]
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Fernando, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
Git flow is followed. :heavy_check_mark:
## To Improve 🙏

- [x] There were some errors while migrating the db so could not run the tests. Kindly see the screenshot below.

issue

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by fernando-silvabr66** [comment]
Hi @SajjadAhmad14 . Thanks for your reply.

I have tried to replicate this error in my environment, by doing a db:reset and a db:migrate:

image

but I can not get the same error. 

Do you have any clue on how I can check for it (sorry my question mark is not working properly).

Thanks in advance.

**Comment by SajjadAhmad14** [comment]
Hi, so you don't to add default values to counters as it's not a requirement. So you can delete this migration. Try running rails db:migrate after deleting this migration.

**Review by mukhammadrizooff — APPROVED** [review]
Hi @fernando-silvabr66, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 
- Descriptive `PR` description and `Commit` history ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
